// ===== data.js =====
const symbolCategories = {
    '希腊字母': [
        { char: 'α', latex: '\\alpha' },
        { char: 'β', latex: '\\beta' },
        { char: 'γ', latex: '\\gamma' },
        { char: 'δ', latex: '\\delta' },
        { char: 'ε', latex: '\\epsilon' },
        { char: 'ζ', latex: '\\zeta' },
        { char: 'η', latex: '\\eta' },
        { char: 'θ', latex: '\\theta' },
        { char: 'ι', latex: '\\iota' },
        { char: 'κ', latex: '\\kappa' },
        { char: 'λ', latex: '\\lambda' },
        { char: 'μ', latex: '\\mu' },
        { char: 'ν', latex: '\\nu' },
        { char: 'ξ', latex: '\\xi' },
        { char: 'π', latex: '\\pi' },
        { char: 'ρ', latex: '\\rho' },
        { char: 'σ', latex: '\\sigma' },
        { char: 'τ', latex: '\\tau' },
        { char: 'υ', latex: '\\upsilon' },
        { char: 'φ', latex: '\\phi' },
        { char: 'χ', latex: '\\chi' },
        { char: 'ψ', latex: '\\psi' },
        { char: 'ω', latex: '\\omega' },
        { char: 'Γ', latex: '\\Gamma' },
        { char: 'Δ', latex: '\\Delta' },
        { char: 'Θ', latex: '\\Theta' },
        { char: 'Λ', latex: '\\Lambda' },
        { char: 'Ξ', latex: '\\Xi' },
        { char: 'Π', latex: '\\Pi' },
        { char: 'Σ', latex: '\\Sigma' },
        { char: 'Φ', latex: '\\Phi' },
        { char: 'Ψ', latex: '\\Psi' },
        { char: 'Ω', latex: '\\Omega' },
        { char: '∞', latex: '\\infty' },
        { char: '∂', latex: '\\partial' },
        { char: '∇', latex: '\\nabla' },
    ],
    '运算符': [
        { char: '+', latex: '+' },
        { char: '−', latex: '-' },
        { char: '×', latex: '\\times' },
        { char: '÷', latex: '\\div' },
        { char: '±', latex: '\\pm' },
        { char: '∓', latex: '\\mp' },
        { char: '·', latex: '\\cdot' },
        { char: '∗', latex: '\\ast' },
        { char: '⋆', latex: '\\star' },
        { char: '∘', latex: '\\circ' },
        { char: '•', latex: '\\bullet' },
        { char: '⊕', latex: '\\oplus' },
        { char: '⊖', latex: '\\ominus' },
        { char: '⊗', latex: '\\otimes' },
        { char: '⊘', latex: '\\oslash' },
        { char: '⊙', latex: '\\odot' },
        { char: '†', latex: '\\dagger' },
        { char: '‡', latex: '\\ddagger' },
        { char: '√', latex: '\\surd' },
        { char: '∠', latex: '\\angle' },
        { char: '△', latex: '\\triangle' },
        { char: '□', latex: '\\square' },
        { char: '◇', latex: '\\diamond' },
    ],
    '关系符': [
        { char: '=', latex: '=' },
        { char: '≠', latex: '\\neq' },
        { char: '<', latex: '<' },
        { char: '>', latex: '>' },
        { char: '≤', latex: '\\leq' },
        { char: '≥', latex: '\\geq' },
        { char: '≪', latex: '\\ll' },
        { char: '≫', latex: '\\gg' },
        { char: '≈', latex: '\\approx' },
        { char: '∼', latex: '\\sim' },
        { char: '≃', latex: '\\simeq' },
        { char: '≅', latex: '\\cong' },
        { char: '≡', latex: '\\equiv' },
        { char: '∝', latex: '\\propto' },
        { char: '∈', latex: '\\in' },
        { char: '∉', latex: '\\notin' },
        { char: '⊂', latex: '\\subset' },
        { char: '⊃', latex: '\\supset' },
        { char: '⊆', latex: '\\subseteq' },
        { char: '⊇', latex: '\\supseteq' },
        { char: '∪', latex: '\\cup' },
        { char: '∩', latex: '\\cap' },
        { char: '∧', latex: '\\land' },
        { char: '∨', latex: '\\lor' },
        { char: '¬', latex: '\\neg' },
        { char: '∀', latex: '\\forall' },
        { char: '∃', latex: '\\exists' },
        { char: '∅', latex: '\\emptyset' },
        { char: '⊥', latex: '\\perp' },
        { char: '∥', latex: '\\parallel' },
        { char: '∴', latex: '\\therefore' },
        { char: '∵', latex: '\\because' },
    ],
    '箭头': [
        { char: '→', latex: '\\rightarrow' },
        { char: '←', latex: '\\leftarrow' },
        { char: '↔', latex: '\\leftrightarrow' },
        { char: '⇒', latex: '\\Rightarrow' },
        { char: '⇐', latex: '\\Leftarrow' },
        { char: '⇔', latex: '\\Leftrightarrow' },
        { char: '↦', latex: '\\mapsto' },
        { char: '↑', latex: '\\uparrow' },
        { char: '↓', latex: '\\downarrow' },
        { char: '↕', latex: '\\updownarrow' },
        { char: '⇑', latex: '\\Uparrow' },
        { char: '⇓', latex: '\\Downarrow' },
        { char: '⟶', latex: '\\longrightarrow' },
        { char: '⟵', latex: '\\longleftarrow' },
        { char: '⟷', latex: '\\longleftrightarrow' },
        { char: '⟹', latex: '\\Longrightarrow' },
    ],
    '函数': [
        { char: 'sin', latex: '\\sin' },
        { char: 'cos', latex: '\\cos' },
        { char: 'tan', latex: '\\tan' },
        { char: 'cot', latex: '\\cot' },
        { char: 'sec', latex: '\\sec' },
        { char: 'csc', latex: '\\csc' },
        { char: 'arcsin', latex: '\\arcsin' },
        { char: 'arccos', latex: '\\arccos' },
        { char: 'arctan', latex: '\\arctan' },
        { char: 'log', latex: '\\log' },
        { char: 'ln', latex: '\\ln' },
        { char: 'exp', latex: '\\exp' },
        { char: 'max', latex: '\\max' },
        { char: 'min', latex: '\\min' },
        { char: 'sup', latex: '\\sup' },
        { char: 'inf', latex: '\\inf' },
        { char: 'det', latex: '\\det' },
        { char: 'gcd', latex: '\\gcd' },
        { char: 'mod', latex: '\\mod' },
        { char: 'lim', latex: '\\lim' },
    ],
    '结构': [
        { char: 'a/b', latex: '\\frac{}{}', cursor: 6, noSymbol: true },
        { char: '√x', latex: '\\sqrt{}', cursor: 6, noSymbol: true },
        { char: 'ⁿ√x', latex: '\\sqrt[]{}', cursor: 7, noSymbol: true },
        { char: 'xᵃ', latex: '^{}', cursor: 2, noSymbol: true },
        { char: 'xₐ', latex: '_{}', cursor: 2, noSymbol: true },
        { char: 'xₐᵇ', latex: '_{}^{}', cursor: 6, noSymbol: true },
        { char: '∫ab', latex: '\\int_{}^{}', cursor: 6, noSymbol: true },
        { char: '∬', latex: '\\iint_{}^{}', cursor: 7, noSymbol: true },
        { char: '∭', latex: '\\iiint_{}^{}', cursor: 8, noSymbol: true },
        { char: '∑', latex: '\\sum_{}^{}', cursor: 6, noSymbol: true },
        { char: '∏', latex: '\\prod_{}^{}', cursor: 7, noSymbol: true },
        { char: 'lim', latex: '\\lim_{ \\to }', cursor: 11, noSymbol: true },
    ],
    '括号': [
        { char: '( )', latex: '\\left( \\right)', cursor: 7, noSymbol: true },
        { char: '[ ]', latex: '\\left[ \\right]', cursor: 7, noSymbol: true },
        { char: '{ }', latex: '\\left\\{ \\right\\}', cursor: 8, noSymbol: true },
        { char: '| |', latex: '\\left| \\right|', cursor: 7, noSymbol: true },
        { char: '‖ ‖', latex: '\\left\\| \\right\\|', cursor: 8, noSymbol: true },
        { char: '⟨ ⟩', latex: '\\langle \\rangle', cursor: 9, noSymbol: true },
        { char: '⌈ ⌉', latex: '\\lceil \\rceil', cursor: 8, noSymbol: true },
        { char: '⌊ ⌋', latex: '\\lfloor \\rfloor', cursor: 8, noSymbol: true },
    ],
    '矩阵': [
        { char: '( )矩阵', latex: '\\begin{pmatrix}\n & \\\\\n & \n\\end{pmatrix}', cursor: 16, noSymbol: true },
        { char: '[ ]矩阵', latex: '\\begin{bmatrix}\n & \\\\\n & \n\\end{bmatrix}', cursor: 16, noSymbol: true },
        { char: '| |矩阵', latex: '\\begin{vmatrix}\n & \\\\\n & \n\\end{vmatrix}', cursor: 16, noSymbol: true },
        { char: '行列式', latex: '\\begin{vmatrix}\n & \\\\\n & \n\\end{vmatrix}', cursor: 16, noSymbol: true },
        { char: 'cases', latex: '\\begin{cases}\n & \\\\\n & \n\\end{cases}', cursor: 15, noSymbol: true },
        { char: 'aligned', latex: '\\begin{aligned}\n & \\\\\n & \n\\end{aligned}', cursor: 17, noSymbol: true },
    ],
    '其他': [
        { char: 'ℝ', latex: '\\mathbb{R}' },
        { char: 'ℂ', latex: '\\mathbb{C}' },
        { char: 'ℕ', latex: '\\mathbb{N}' },
        { char: 'ℤ', latex: '\\mathbb{Z}' },
        { char: 'ℚ', latex: '\\mathbb{Q}' },
        { char: 'ℏ', latex: '\\hbar' },
        { char: 'ℓ', latex: '\\ell' },
        { char: '℘', latex: '\\wp' },
        { char: 'ℑ', latex: '\\Im' },
        { char: 'ℜ', latex: '\\Re' },
        { char: '′', latex: '\\prime' },
        { char: '°', latex: '^{\\circ}' },
        { char: '∇', latex: '\\nabla' },
        { char: '∂', latex: '\\partial' },
        { char: 'text', latex: '\\text{}', cursor: 6, noSymbol: true },
        { char: 'mathrm', latex: '\\mathrm{}', cursor: 8, noSymbol: true },
        { char: 'mathbf', latex: '\\mathbf{}', cursor: 8, noSymbol: true },
        { char: 'mathcal', latex: '\\mathcal{}', cursor: 9, noSymbol: true },
        { char: 'mathfrak', latex: '\\mathfrak{}', cursor: 9, noSymbol: true },
    ],
};

const presetFormulas = [
    { name: '欧拉恒等式', latex: 'e^{i\\pi} + 1 = 0' },
    { name: '二次方程求根', latex: 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}' },
    { name: '勾股定理', latex: 'a^2 + b^2 = c^2' },
    { name: '微积分基本定理', latex: '\\int_a^b f(x)\\,dx = F(b) - F(a)' },
    { name: '泰勒展开', latex: 'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n' },
    { name: '傅里叶变换', latex: 'F(\\omega) = \\int_{-\\infty}^{\\infty} f(t)e^{-i\\omega t}\\,dt' },
    { name: '正态分布', latex: 'f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}' },
    { name: '麦克斯韦方程组', latex: '\\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\varepsilon_0}' },
    { name: '牛顿第二定律', latex: '\\mathbf{F} = m\\mathbf{a}' },
    { name: '质能方程', latex: 'E = mc^2' },
    { name: '黄金比例', latex: '\\varphi = \\frac{1+\\sqrt{5}}{2}' },
    { name: '矩阵乘法', latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} \\begin{pmatrix} x \\\\ y \\end{pmatrix} = \\begin{pmatrix} ax+by \\\\ cx+dy \\end{pmatrix}' },
];

const toolbarButtons = [
    { label: '分数', insert: '\\frac{}{}', cursor: 6 },
    { label: '根号', insert: '\\sqrt{}', cursor: 6 },
    { label: '上标', insert: '^{}', cursor: 2 },
    { label: '下标', insert: '_{}', cursor: 2 },
    { label: '积分', insert: '\\int_{}^{}', cursor: 6 },
    { label: '求和', insert: '\\sum_{}^{}', cursor: 6 },
    { label: '极限', insert: '\\lim_{x \\to }', cursor: 11 },
    { label: '矩阵', insert: '\\begin{pmatrix}\n & \\\\\n & \n\\end{pmatrix}', cursor: 16 },
];